# Generated by Django 5.2.5 on 2026-04-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Шинэ төсөл"),
                    ("in_progress", "Хийгдэж буй"),
                    ("maintenance", "Арчилгааны шатанд"),
                    ("half_balance", "Хагас гүйцэтгэлтэй"),
                    ("completed", "Дууссан"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
