# Generated by Django 5.2.5 on 2026-04-13 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_project_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Даалгаврын нэр"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("review", "Review"),
                            ("completed", "Completed"),
                            ("stuck", "Stuck"),
                            ("working", "Working on it"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="Төлөв",
                    ),
                ),
                (
                    "number_test",
                    models.IntegerField(default=0, verbose_name="Тоон үзүүлэлт"),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Тэмдэглэл"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дуусах хугацаа"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хариуцагч",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.project",
                        verbose_name="Хамаарах төсөл",
                    ),
                ),
            ],
            options={
                "verbose_name": "Даалгавар",
                "verbose_name_plural": "Даалгаврууд",
                "ordering": ["created_at"],
            },
        ),
    ]
