# Generated by Django 5.2.5 on 2026-05-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_comment_commentfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="tasks/attachments/%Y/%m/%d/"
            ),
        ),
    ]
