# Generated by Django 5.2.5 on 2026-05-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("tasks", "0005_task_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="commentfile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tasks/attachments/%Y/%m/%d/",
                verbose_name="Хавсаргасан файл",
            ),
        ),
    ]
