# Generated by Django 5.2.5 on 2026-05-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_comment_organization_commentfile_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentfile",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
